import { ChangeDetectionStrategy, Component, inject, input, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { RouterLink } from '@angular/router';
import { ArrowLeft, Check, CheckCircle2, Clock3, CreditCard, ExternalLink, LucideAngularModule, Mail, MapPin, MoreHorizontal, PackageCheck, Printer, Truck } from 'lucide-angular';
import { formatCurrency } from '@nova/shared-utils';
import type { OrderStatus } from '@nova/shared-types';
import { AdminDataService } from '../../core/services/admin-data.service';

@Component({selector:'nova-order-detail',standalone:true,imports:[DatePipe,RouterLink,LucideAngularModule],template:`
@if(order();as current){<div class="detail-page page-enter"><header class="detail-header"><div><a routerLink="/admin/orders"><lucide-icon [img]="ArrowLeft" [size]="15"/>Orders</a><div><h2>{{current.number}}</h2><span class="table-status processing"><i></i>{{current.status}}</span></div><p>{{current.date|date:'MMMM d, y, h:mm a'}} · {{current.items}} items</p></div><div><button class="admin-secondary"><lucide-icon [img]="Printer" [size]="15"/>Print</button><button class="admin-secondary"><lucide-icon [img]="MoreHorizontal" [size]="15"/></button><select class="admin-primary" [value]="current.status" (change)="changeStatus($any($event.target).value)">@for(status of statuses;track status){<option [value]="status">{{status}}</option>}</select></div></header>
<div class="detail-layout"><div class="detail-main"><section class="detail-card"><header><div><lucide-icon [img]="PackageCheck" [size]="18"/><h3>Fulfillment</h3></div><span class="table-status">{{current.fulfillment}}</span></header><div class="order-items">@for(image of current.imageUrls;track image;let i=$index){<div><img [src]="image" alt=""/><div><strong>{{data.products()[(i*7)%data.products().length].name}}</strong><span>{{data.products()[(i*7)%data.products().length].variants[0].name}} · {{data.products()[(i*7)%data.products().length].sku}}</span></div><span>× {{i+1}}</span><b>{{formatCurrency(data.products()[(i*7)%data.products().length].price*(i+1))}}</b></div>}</div><footer><button class="admin-primary"><lucide-icon [img]="Truck" [size]="15"/>Create fulfillment</button><button class="admin-secondary">Add tracking</button></footer></section>
<section class="detail-card"><header><div><lucide-icon [img]="CreditCard" [size]="18"/><h3>Payment</h3></div><span class="table-status active"><i></i>{{current.payment}}</span></header><dl class="payment-summary"><div><dt>Subtotal · {{current.items}} items</dt><dd>{{formatCurrency(current.total*.86)}}</dd></div><div><dt>Shipping · Standard</dt><dd>Complimentary</dd></div><div><dt>Estimated tax</dt><dd>{{formatCurrency(current.total*.08)}}</dd></div><div><dt>Discount · WELCOME10</dt><dd>−{{formatCurrency(current.total*.04)}}</dd></div><div><dt>Total</dt><dd>{{formatCurrency(current.total)}} USD</dd></div></dl></section>
<section class="detail-card timeline-card"><header><div><lucide-icon [img]="Clock3" [size]="18"/><h3>Timeline</h3></div></header><form (submit)="$event.preventDefault()"><div class="timeline-avatar">MR</div><input placeholder="Leave an internal note…"/><button>Post</button></form><div class="timeline"><div><span><lucide-icon [img]="Check" [size]="12"/></span><p>Order marked as {{current.status}}<small>Today, 10:42 AM · Mara Reyes</small></p></div><div><span><lucide-icon [img]="CreditCard" [size]="12"/></span><p>Payment of {{formatCurrency(current.total)}} was processed<small>{{current.date|date:'MMM d, h:mm a'}}</small></p></div><div><span><lucide-icon [img]="Check" [size]="12"/></span><p>Confirmation email was sent to {{current.email}}<small>{{current.date|date:'MMM d, h:mm a'}}</small></p></div><div><span><lucide-icon [img]="PackageCheck" [size]="12"/></span><p>Order {{current.number}} was created<small>{{current.date|date:'MMM d, h:mm a'}}</small></p></div></div></section></div>
<aside class="detail-side"><section class="detail-card customer-card"><header><h3>Customer</h3><a routerLink="/admin/customers/{{current.customerId}}"><lucide-icon [img]="ExternalLink" [size]="14"/></a></header><div class="customer-summary"><span>{{initials(current.customer)}}</span><div><strong>{{current.customer}}</strong><small>{{data.customer(current.customerId)?.orders}} orders</small></div></div><div class="contact-line"><lucide-icon [img]="Mail" [size]="15"/><span>{{current.email}}</span></div><div class="address-block"><div><h4>Shipping address</h4><button>Copy</button></div><p>{{current.customer}}<br/>{{current.address}}<br/>United States</p></div><div class="address-block"><h4>Billing address</h4><p>Same as shipping address</p></div></section><section class="detail-card"><header><h3>Order details</h3></header><dl class="meta-list"><div><dt>Sales channel</dt><dd>Online Store</dd></div><div><dt>Device</dt><dd>Mobile</dd></div><div><dt>Risk level</dt><dd><span class="risk-low">Low</span></dd></div><div><dt>Session</dt><dd>NV-{{current.id.slice(-6)}}</dd></div></dl></section></aside></div></div>}@else{<div class="table-empty detail-missing"><h2>Order not found</h2><a routerLink="/admin/orders">Return to orders</a></div>}`,changeDetection:ChangeDetectionStrategy.OnPush})
export class OrderDetailComponent{readonly ArrowLeft=ArrowLeft;readonly Check=Check;readonly Clock3=Clock3;readonly CreditCard=CreditCard;readonly ExternalLink=ExternalLink;readonly Mail=Mail;readonly MoreHorizontal=MoreHorizontal;readonly PackageCheck=PackageCheck;readonly Printer=Printer;readonly Truck=Truck;readonly id=input.required<string>();readonly data=inject(AdminDataService);readonly formatCurrency=formatCurrency;readonly order=()=>this.data.order(this.id());readonly statuses:OrderStatus[]=['pending','confirmed','processing','shipped','delivered','cancelled'];initials(name:string){return name.split(' ').map(p=>p[0]).join('')}async changeStatus(status:OrderStatus){await this.data.updateOrderStatus(this.id(),status)}}
