import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { RouterLink } from '@angular/router';
import { ChevronLeft, ChevronRight, Download, Filter, MoreHorizontal, Search, SlidersHorizontal, LucideAngularModule } from 'lucide-angular';
import { formatCurrency } from '@nova/shared-utils';
import { AdminDataService } from '../../core/services/admin-data.service';

@Component({ selector:'nova-orders',standalone:true,imports:[DatePipe,RouterLink,LucideAngularModule],template:`
  <div class="feature-page page-enter"><header class="feature-header"><div><h2>Orders</h2><p>Track payment, fulfillment, and the complete customer journey.</p></div><button class="admin-secondary"><lucide-icon [img]="Download" [size]="15" />Export orders</button></header>
  <section class="order-tabs">@for(tab of tabs;track tab.key){<button [class.active]="status()===tab.key" (click)="status.set(tab.key)">{{tab.label}}<span>{{count(tab.key)}}</span></button>}</section>
  <section class="table-panel"><div class="table-toolbar"><div class="table-search"><lucide-icon [img]="Search" [size]="15"/><input [value]="search()" (input)="search.set($any($event.target).value)" placeholder="Search order, customer, or email"/></div><div class="table-filters"><button><lucide-icon [img]="SlidersHorizontal" [size]="15"/>More filters</button><select><option>Newest first</option><option>Oldest first</option><option>Highest total</option></select></div></div>
  <div class="data-table-wrap"><table class="data-table order-table"><thead><tr><th><input type="checkbox"/></th><th>Order</th><th>Date</th><th>Customer</th><th>Payment</th><th>Fulfillment</th><th>Items</th><th>Total</th><th></th></tr></thead><tbody>@for(order of filtered();track order.id){<tr><td><input type="checkbox"/></td><td><a routerLink="/admin/orders/{{order.id}}"><strong>{{order.number}}</strong></a></td><td>{{order.date|date:'MMM d, y'}}<small>{{order.date|date:'h:mm a'}}</small></td><td><a routerLink="/admin/customers/{{order.customerId}}" class="table-person"><i>{{initials(order.customer)}}</i><span><b>{{order.customer}}</b><small>{{order.email}}</small></span></a></td><td><span class="table-status" [class.refunded]="order.payment==='refunded'"><i></i>{{order.payment}}</span></td><td><span class="table-status" [class.processing]="order.status==='processing'" [class.shipped]="order.status==='shipped'"><i></i>{{order.fulfillment}}</span></td><td><div class="item-stack">@for(image of order.imageUrls.slice(0,2);track image){<img [src]="image" alt=""/>}<span>{{order.items}}</span></div></td><td><strong>{{formatCurrency(order.total)}}</strong></td><td><button class="row-menu"><lucide-icon [img]="MoreHorizontal" [size]="16"/></button></td></tr>}@empty{<tr><td colspan="9"><div class="table-empty"><p>No orders match this view.</p></div></td></tr>}</tbody></table></div>
  <footer class="table-pagination"><span>{{filtered().length}} orders</span><div><button disabled><lucide-icon [img]="ChevronLeft" [size]="14"/></button><button class="active">1</button><button>2</button><button>3</button><button><lucide-icon [img]="ChevronRight" [size]="14"/></button></div></footer></section></div>`,changeDetection:ChangeDetectionStrategy.OnPush})
export class OrdersComponent{readonly ChevronLeft=ChevronLeft;readonly ChevronRight=ChevronRight;readonly Download=Download;readonly MoreHorizontal=MoreHorizontal;readonly Search=Search;readonly SlidersHorizontal=SlidersHorizontal;readonly data=inject(AdminDataService);readonly formatCurrency=formatCurrency;readonly search=signal('');readonly status=signal('all');readonly tabs=[{key:'all',label:'All'},{key:'unfulfilled',label:'Unfulfilled'},{key:'processing',label:'Processing'},{key:'shipped',label:'Shipped'},{key:'delivered',label:'Delivered'},{key:'cancelled',label:'Cancelled'}];readonly filtered=computed(()=>{const q=this.search().toLowerCase();return this.data.orders().filter(o=>(this.status()==='all'||(this.status()==='unfulfilled'?o.fulfillment==='Unfulfilled':o.status===this.status()))&&(!q||`${o.number} ${o.customer} ${o.email}`.toLowerCase().includes(q)))});count(key:string){return key==='all'?this.data.orders().length:key==='unfulfilled'?this.data.orders().filter(o=>o.fulfillment==='Unfulfilled').length:this.data.orders().filter(o=>o.status===key).length}initials(name:string){return name.split(' ').map(p=>p[0]).join('')}}
