import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { RouterLink } from '@angular/router';
import { ChevronLeft, ChevronRight, Download, Mail, MoreHorizontal, Plus, Search, SlidersHorizontal, LucideAngularModule } from 'lucide-angular';
import { formatCurrency } from '@nova/shared-utils';
import { AdminDataService } from '../../core/services/admin-data.service';

@Component({selector:'nova-customers',standalone:true,imports:[DatePipe,RouterLink,LucideAngularModule],template:`
<div class="feature-page page-enter"><header class="feature-header"><div><h2>Customers</h2><p>Understand relationships, order behavior, and lifetime value.</p></div><div><button class="admin-secondary"><lucide-icon [img]="Download" [size]="15"/>Export</button><button class="admin-primary"><lucide-icon [img]="Plus" [size]="15"/>Add customer</button></div></header>
<section class="customer-summary-grid"><article><span>Total customers</span><strong>{{data.customers().length}}</strong><small><b>+8.2%</b> this month</small></article><article><span>New this month</span><strong>12</strong><small><b>+14.1%</b> vs last month</small></article><article><span>Returning rate</span><strong>42.8%</strong><small><b>+3.4%</b> this quarter</small></article><article><span>Average lifetime value</span><strong>{{formatCurrency(avgLtv())}}</strong><small><b>+6.7%</b> this quarter</small></article></section>
<section class="table-panel"><div class="table-toolbar"><div class="table-search"><lucide-icon [img]="Search" [size]="15"/><input [value]="search()" (input)="search.set($any($event.target).value)" placeholder="Search name or email"/></div><div class="table-filters"><select><option>All customers</option><option>Repeat customers</option><option>New customers</option></select><button><lucide-icon [img]="SlidersHorizontal" [size]="15"/>More filters</button></div></div><div class="data-table-wrap"><table class="data-table customer-table"><thead><tr><th><input type="checkbox"/></th><th>Customer</th><th>Location</th><th>Orders</th><th>Total spent</th><th>Average order</th><th>Last order</th><th>Joined</th><th></th></tr></thead><tbody>@for(customer of filtered();track customer.id){<tr><td><input type="checkbox"/></td><td><a routerLink="/admin/customers/{{customer.id}}" class="table-person"><i>{{initials(customer.name)}}</i><span><b>{{customer.name}}</b><small>{{customer.email}}</small></span></a></td><td>{{customer.city}}</td><td><strong>{{customer.orders}}</strong></td><td><strong>{{formatCurrency(customer.totalSpent)}}</strong></td><td>{{formatCurrency(customer.averageOrder)}}</td><td>{{customer.lastOrder|date:'MMM d, y'}}</td><td>{{customer.joined|date:'MMM d, y'}}</td><td><button class="row-menu"><lucide-icon [img]="MoreHorizontal" [size]="16"/></button></td></tr>}</tbody></table></div><footer class="table-pagination"><span>{{filtered().length}} customers</span><div><button disabled><lucide-icon [img]="ChevronLeft" [size]="14"/></button><button class="active">1</button><button>2</button><button><lucide-icon [img]="ChevronRight" [size]="14"/></button></div></footer></section></div>`,changeDetection:ChangeDetectionStrategy.OnPush})
export class CustomersComponent{readonly ChevronLeft=ChevronLeft;readonly ChevronRight=ChevronRight;readonly Download=Download;readonly MoreHorizontal=MoreHorizontal;readonly Plus=Plus;readonly Search=Search;readonly SlidersHorizontal=SlidersHorizontal;readonly data=inject(AdminDataService);readonly formatCurrency=formatCurrency;readonly search=signal('');readonly filtered=computed(()=>{const q=this.search().toLowerCase();return this.data.customers().filter(c=>!q||`${c.name} ${c.email}`.toLowerCase().includes(q))});readonly avgLtv=computed(()=>this.data.customers().reduce((s,c)=>s+c.totalSpent,0)/this.data.customers().length);initials(name:string){return name.split(' ').map(p=>p[0]).join('')}}
