import { ChangeDetectionStrategy, Component, inject, input } from '@angular/core';
import { DatePipe } from '@angular/common';
import { RouterLink } from '@angular/router';
import { ArrowLeft, Edit3, Mail, MapPin, MessageSquare, MoreHorizontal, Phone, Plus, ShoppingBag, Tag, UserRound, LucideAngularModule } from 'lucide-angular';
import { formatCurrency } from '@nova/shared-utils';
import { AdminDataService } from '../../core/services/admin-data.service';

@Component({selector:'nova-customer-detail',standalone:true,imports:[DatePipe,RouterLink,LucideAngularModule],template:`
@if(customer();as c){<div class="detail-page page-enter"><header class="detail-header customer-detail-head"><div><a routerLink="/admin/customers"><lucide-icon [img]="ArrowLeft" [size]="15"/>Customers</a><div class="profile-heading"><span>{{initials(c.name)}}</span><div><h2>{{c.name}}</h2><p>Customer since {{c.joined|date:'MMMM y'}} · {{c.city}}</p></div></div></div><div><button class="admin-secondary"><lucide-icon [img]="Edit3" [size]="15"/>Edit</button><button class="admin-secondary"><lucide-icon [img]="MoreHorizontal" [size]="15"/></button></div></header>
<section class="customer-kpis"><article><span>Lifetime value</span><strong>{{formatCurrency(c.totalSpent)}}</strong><small>Top 18% of customers</small></article><article><span>Total orders</span><strong>{{c.orders}}</strong><small>{{Math.round(c.orders/1.4)}} fulfilled</small></article><article><span>Average order</span><strong>{{formatCurrency(c.averageOrder)}}</strong><small>+9% above store avg.</small></article><article><span>Last order</span><strong>{{c.lastOrder|date:'MMM d'}}</strong><small>{{daysSince(c.lastOrder)}} days ago</small></article></section>
<div class="detail-layout"><div class="detail-main"><section class="detail-card"><header><div><lucide-icon [img]="ShoppingBag" [size]="18"/><h3>Order history</h3></div><a routerLink="/admin/orders">View all orders</a></header><div class="mini-order-list">@for(order of customerOrders().slice(0,5);track order.id){<a routerLink="/admin/orders/{{order.id}}"><span><strong>{{order.number}}</strong><small>{{order.date|date:'MMM d, y'}}</small></span><span class="table-status">{{order.status}}</span><span>{{order.items}} items</span><b>{{formatCurrency(order.total)}}</b></a>}</div></section><section class="detail-card notes-card"><header><div><lucide-icon [img]="MessageSquare" [size]="18"/><h3>Notes</h3></div></header><textarea rows="4" [value]="c.notes" placeholder="Add context only your team can see…"></textarea><footer><span>Notes are private to staff.</span><button class="admin-primary">Save note</button></footer></section><section class="detail-card timeline-card"><header><div><lucide-icon [img]="UserRound" [size]="18"/><h3>Customer activity</h3></div></header><div class="timeline"><div><span><lucide-icon [img]="ShoppingBag" [size]="12"/></span><p>Placed order {{customerOrders()[0]?.number}}<small>{{c.lastOrder|date:'MMM d, h:mm a'}}</small></p></div><div><span><lucide-icon [img]="UserRound" [size]="12"/></span><p>Customer account created<small>{{c.joined|date:'MMM d, y'}}</small></p></div></div></section></div>
<aside class="detail-side"><section class="detail-card"><header><h3>Contact</h3><button><lucide-icon [img]="Edit3" [size]="14"/></button></header><div class="contact-line"><lucide-icon [img]="Mail" [size]="15"/><span>{{c.email}}</span></div><div class="contact-line"><lucide-icon [img]="Phone" [size]="15"/><span>+1 (503) 555-01{{c.id.slice(-2)}}</span></div></section><section class="detail-card"><header><h3>Default address</h3><button><lucide-icon [img]="Edit3" [size]="14"/></button></header><div class="contact-line address-contact"><lucide-icon [img]="MapPin" [size]="15"/><p>{{c.name}}<br/>125 Meridian Street<br/>{{c.city}} 97205<br/>United States</p></div></section><section class="detail-card"><header><h3>Tags</h3><button><lucide-icon [img]="Plus" [size]="14"/></button></header><div class="customer-tags"><span>Repeat customer</span><span>Newsletter</span><span>High intent</span></div></section><section class="detail-card"><header><h3>Marketing</h3></header><dl class="meta-list"><div><dt>Email</dt><dd><span class="risk-low">Subscribed</span></dd></div><div><dt>SMS</dt><dd>Not subscribed</dd></div></dl></section></aside></div></div>}`,changeDetection:ChangeDetectionStrategy.OnPush})
export class CustomerDetailComponent{readonly ArrowLeft=ArrowLeft;readonly Edit3=Edit3;readonly Mail=Mail;readonly MapPin=MapPin;readonly MessageSquare=MessageSquare;readonly MoreHorizontal=MoreHorizontal;readonly Phone=Phone;readonly Plus=Plus;readonly ShoppingBag=ShoppingBag;readonly Tag=Tag;readonly UserRound=UserRound;readonly Math=Math;readonly id=input.required<string>();readonly data=inject(AdminDataService);readonly formatCurrency=formatCurrency;readonly customer=()=>this.data.customer(this.id());readonly customerOrders=()=>this.data.orders().filter(o=>o.customerId===this.id());initials(name:string){return name.split(' ').map(p=>p[0]).join('')}daysSince(date:string){return Math.floor((Date.now()-new Date(date).getTime())/86400000)}}
