import { ChangeDetectionStrategy, Component, computed, inject, signal } from '@angular/core';
import { DatePipe } from '@angular/common';
import { RouterLink } from '@angular/router';
import { Archive, ArrowDown, ArrowUp, ChevronLeft, ChevronRight, Download, Filter, MoreHorizontal, Plus, Search, SlidersHorizontal, LucideAngularModule } from 'lucide-angular';
import { formatCurrency } from '@nova/shared-utils';
import { AdminDataService, type AdminProduct } from '../../core/services/admin-data.service';

@Component({
  selector: 'nova-products', standalone: true,
  imports: [DatePipe, RouterLink, LucideAngularModule],
  template: `
    <div class="feature-page page-enter">
      <header class="feature-header"><div><h2>Products</h2><p>Manage your catalog, prices, variants, and publishing status.</p></div><div><button class="admin-secondary"><lucide-icon [img]="Download" [size]="15" />Export</button><a class="admin-primary" routerLink="/admin/products/new"><lucide-icon [img]="Plus" [size]="15" />Add product</a></div></header>
      <section class="summary-strip"><div><span>All products</span><strong>{{ data.products().length }}</strong></div><div><span>Active</span><strong>{{ data.activeProducts() }}</strong></div><div><span>Draft</span><strong>{{ draftCount() }}</strong></div><div><span>Archived</span><strong>{{ archivedCount() }}</strong></div><div><span>Inventory value</span><strong>{{ formatCurrency(inventoryValue()) }}</strong></div></section>
      <section class="table-panel">
        <div class="table-toolbar"><div class="table-search"><lucide-icon [img]="Search" [size]="15" /><input [value]="search()" (input)="search.set($any($event.target).value); page.set(1)" placeholder="Search products or SKU" /></div><div class="table-filters"><select [value]="status()" (change)="status.set($any($event.target).value); page.set(1)"><option value="all">All statuses</option><option value="active">Active</option><option value="draft">Draft</option><option value="archived">Archived</option></select><select [value]="category()" (change)="category.set($any($event.target).value); page.set(1)"><option value="all">All categories</option>@for (item of categories(); track item) { <option [value]="item">{{ item }}</option> }</select><button><lucide-icon [img]="SlidersHorizontal" [size]="15" />More filters</button></div></div>
        @if (selection().size) { <div class="bulk-bar"><strong>{{ selection().size }} selected</strong><button (click)="setSelectedStatus('active')">Set active</button><button (click)="setSelectedStatus('draft')">Set draft</button><button><lucide-icon [img]="Archive" [size]="13" /> Archive</button><button class="bulk-clear" (click)="selection.set(newSet())">Clear</button></div> }
        <div class="data-table-wrap"><table class="data-table product-table"><thead><tr><th class="checkbox-cell"><input type="checkbox" [checked]="allSelected()" (change)="toggleAll()" /></th><th><button (click)="setSort('name')">Product <lucide-icon [img]="sortIcon('name')" [size]="12" /></button></th><th>Category</th><th><button (click)="setSort('status')">Status <lucide-icon [img]="sortIcon('status')" [size]="12" /></button></th><th><button (click)="setSort('inventory')">Inventory <lucide-icon [img]="sortIcon('inventory')" [size]="12" /></button></th><th><button (click)="setSort('price')">Price <lucide-icon [img]="sortIcon('price')" [size]="12" /></button></th><th><button (click)="setSort('updatedAt')">Updated <lucide-icon [img]="sortIcon('updatedAt')" [size]="12" /></button></th><th></th></tr></thead>
          <tbody>@for (product of pagedProducts(); track product.id) { <tr><td class="checkbox-cell"><input type="checkbox" [checked]="selection().has(product.id)" (change)="toggle(product.id)" /></td><td><a class="product-cell" routerLink="/admin/products/{{product.id}}"><img [src]="product.imageUrl" alt="" /><span><strong>{{ product.name }}</strong><small>{{ product.sku }}</small></span></a></td><td>{{ product.category }}</td><td><span class="table-status" [class.active]="product.status === 'active'" [class.draft]="product.status === 'draft'" [class.archived]="product.status === 'archived'"><i></i>{{ product.status }}</span></td><td><div class="inventory-cell"><strong [class.low]="product.inventory <= 8">{{ product.inventory }}</strong><span>{{ product.variants.length }} variant{{ product.variants.length === 1 ? '' : 's' }}</span></div></td><td><strong>{{ formatCurrency(product.price) }}</strong></td><td>{{ product.updatedAt | date:'MMM d, y' }}</td><td><button class="row-menu" aria-label="Product actions"><lucide-icon [img]="MoreHorizontal" [size]="16" /></button></td></tr> } @empty { <tr><td colspan="8"><div class="table-empty"><p>No products match these filters.</p><button (click)="resetFilters()">Reset filters</button></div></td></tr> }</tbody></table></div>
        <footer class="table-pagination"><span>Showing {{ rangeStart() }}–{{ rangeEnd() }} of {{ filteredProducts().length }} products</span><div><button [disabled]="page() === 1" (click)="page.set(page()-1)"><lucide-icon [img]="ChevronLeft" [size]="14" /></button>@for (item of pages(); track item) { <button [class.active]="page() === item" (click)="page.set(item)">{{ item }}</button> }<button [disabled]="page() === pages().length" (click)="page.set(page()+1)"><lucide-icon [img]="ChevronRight" [size]="14" /></button></div></footer>
      </section>
    </div>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProductsComponent {
  readonly Archive = Archive; readonly ArrowDown = ArrowDown; readonly ArrowUp = ArrowUp; readonly ChevronLeft = ChevronLeft; readonly ChevronRight = ChevronRight; readonly Download = Download; readonly MoreHorizontal = MoreHorizontal; readonly Plus = Plus; readonly Search = Search; readonly SlidersHorizontal = SlidersHorizontal;
  readonly data = inject(AdminDataService); readonly formatCurrency = formatCurrency; readonly search = signal(''); readonly status = signal('all'); readonly category = signal('all'); readonly sort = signal<keyof AdminProduct>('updatedAt'); readonly direction = signal<'asc'|'desc'>('desc'); readonly page = signal(1); readonly pageSize = 10; readonly selection = signal<Set<string>>(new Set());
  readonly categories = computed(() => [...new Set(this.data.products().map((p) => p.category))].sort()); readonly draftCount = computed(() => this.data.products().filter((p) => p.status === 'draft').length); readonly archivedCount = computed(() => this.data.products().filter((p) => p.status === 'archived').length); readonly inventoryValue = computed(() => this.data.products().reduce((sum,p) => sum+p.cost*p.inventory,0));
  readonly filteredProducts = computed(() => { const q=this.search().toLowerCase(); return [...this.data.products()].filter((p) => (!q || `${p.name} ${p.sku}`.toLowerCase().includes(q)) && (this.status()==='all'||p.status===this.status()) && (this.category()==='all'||p.category===this.category())).sort((a,b) => { const av=a[this.sort()], bv=b[this.sort()]; const cmp=typeof av==='number'&&typeof bv==='number'?av-bv:String(av).localeCompare(String(bv)); return this.direction()==='asc'?cmp:-cmp; }); });
  readonly pagedProducts = computed(() => this.filteredProducts().slice((this.page()-1)*this.pageSize,this.page()*this.pageSize)); readonly pages = computed(() => Array.from({length:Math.max(1,Math.ceil(this.filteredProducts().length/this.pageSize))},(_,i)=>i+1)); readonly rangeStart = computed(() => this.filteredProducts().length ? (this.page()-1)*this.pageSize+1 : 0); readonly rangeEnd = computed(() => Math.min(this.page()*this.pageSize,this.filteredProducts().length)); readonly allSelected = computed(() => this.pagedProducts().length > 0 && this.pagedProducts().every((p) => this.selection().has(p.id)));
  setSort(key:keyof AdminProduct){if(this.sort()===key)this.direction.set(this.direction()==='asc'?'desc':'asc');else{this.sort.set(key);this.direction.set('asc')}} sortIcon(key:keyof AdminProduct){return this.sort()===key&&this.direction()==='asc'?ArrowUp:ArrowDown} newSet(){return new Set<string>()} toggle(id:string){const next=new Set(this.selection());next.has(id)?next.delete(id):next.add(id);this.selection.set(next)} toggleAll(){const next=new Set(this.selection());this.allSelected()?this.pagedProducts().forEach(p=>next.delete(p.id)):this.pagedProducts().forEach(p=>next.add(p.id));this.selection.set(next)}
  setSelectedStatus(status:'active'|'draft'){const ids=this.selection();this.data.products.update(items=>items.map(item=>ids.has(item.id)?{...item,status}:item));this.selection.set(new Set())} resetFilters(){this.search.set('');this.status.set('all');this.category.set('all');this.page.set(1)}
}
