import { ChangeDetectionStrategy, Component, effect, inject, input, signal } from '@angular/core';
import { FormArray, FormBuilder, ReactiveFormsModule, Validators } from '@angular/forms';
import { Router, RouterLink } from '@angular/router';
import { ArrowLeft, Check, ChevronDown, ImagePlus, LucideAngularModule, Plus, Save, Trash2, UploadCloud } from 'lucide-angular';
import { AdminDataService, type AdminProduct } from '../../core/services/admin-data.service';

@Component({
  selector: 'nova-product-editor', standalone: true,
  imports: [ReactiveFormsModule, RouterLink, LucideAngularModule],
  template: `
    <form class="editor-page page-enter" [formGroup]="form" (ngSubmit)="save()">
      <header class="editor-header"><div><a routerLink="/admin/products"><lucide-icon [img]="ArrowLeft" [size]="15" />Products</a><h2>{{ id() ? 'Edit product' : 'Add product' }}</h2><p>{{ id() ? form.controls.name.value : 'Create a new object for the Nova collection.' }}</p></div><div><button type="button" class="admin-secondary" routerLink="/admin/products">Discard</button><button type="submit" class="admin-primary" [disabled]="form.invalid || saving()"><lucide-icon [img]="Save" [size]="15" />{{ saving() ? 'Saving…' : 'Save product' }}</button></div></header>
      @if (saved()) { <div class="save-toast"><lucide-icon [img]="Check" [size]="15" />Product saved successfully.</div> }
      <div class="editor-layout"><div class="editor-main">
        <section class="editor-card"><header><h3>Product information</h3><p>Core details customers see across the storefront.</p></header><div class="editor-fields"><label class="field-wide">Name<input formControlName="name" placeholder="e.g. Nova Carry Backpack" /></label><label class="field-wide">Slug<div class="slug-input"><span>products/</span><input formControlName="slug" /></div></label><label class="field-wide">Description<textarea rows="6" formControlName="description" placeholder="Describe the materials, purpose, and point of view…"></textarea><small>{{ form.controls.description.value.length }} characters</small></label></div></section>
        <section class="editor-card"><header><h3>Media</h3><p>Add product photography in the order it should appear.</p></header><div class="media-grid">@if (form.controls.imageUrl.value) { <div class="media-preview"><img [src]="form.controls.imageUrl.value" alt="Product preview" /><button type="button" (click)="form.controls.imageUrl.setValue('')"><lucide-icon [img]="Trash2" [size]="14" /></button></div> }<label class="upload-tile"><lucide-icon [img]="UploadCloud" [size]="22" /><strong>Add images</strong><span>PNG, JPG or WebP · demo URL</span><input formControlName="imageUrl" placeholder="Paste image URL" /></label></div></section>
        <section class="editor-card"><header><h3>Pricing</h3><p>Set customer pricing and internal cost.</p></header><div class="editor-fields editor-fields--three"><label>Price<div class="money-input"><span>$</span><input type="number" formControlName="price" /></div></label><label>Compare-at price<div class="money-input"><span>$</span><input type="number" formControlName="comparePrice" /></div></label><label>Cost per item<div class="money-input"><span>$</span><input type="number" formControlName="cost" /></div></label></div><div class="margin-preview"><span>Margin <strong>{{ margin() }}%</strong></span><span>Profit <strong>&#36;{{ profit() }}</strong></span></div></section>
        <section class="editor-card"><header><div><h3>Variants</h3><p>Manage options such as finish, color, and size.</p></div><button type="button" class="text-button" (click)="addVariant()"><lucide-icon [img]="Plus" [size]="14" />Add variant</button></header><div formArrayName="variants" class="variant-table"><div class="variant-table__head"><span>Name</span><span>SKU</span><span>Price</span><span>Inventory</span><span></span></div>@for (variant of variants.controls; track $index; let i=$index) { <div [formGroupName]="i"><input formControlName="name" /><input formControlName="sku" /><input type="number" formControlName="price" /><input type="number" formControlName="inventory" /><button type="button" (click)="removeVariant(i)" [disabled]="variants.length===1"><lucide-icon [img]="Trash2" [size]="14" /></button></div> }</div></section>
        <section class="editor-card"><header><h3>Search engine listing</h3><p>Control how this product appears in search results.</p></header><div class="seo-preview"><span>Nova Supply</span><strong>{{ form.controls.seoTitle.value || form.controls.name.value || 'Product title' }}</strong><p>{{ form.controls.seoDescription.value || 'A concise product description will appear here.' }}</p></div><div class="editor-fields"><label class="field-wide">Page title<input formControlName="seoTitle" /><small>{{ form.controls.seoTitle.value.length }}/60</small></label><label class="field-wide">Meta description<textarea rows="3" formControlName="seoDescription"></textarea><small>{{ form.controls.seoDescription.value.length }}/160</small></label></div></section>
      </div><aside class="editor-side">
        <section class="editor-card"><header><h3>Status</h3></header><div class="status-options">@for (item of ['active','draft','archived']; track item) { <label><input type="radio" formControlName="status" [value]="item" /><span><i></i><strong>{{ item }}</strong><small>{{ item === 'active' ? 'Visible on storefront' : item === 'draft' ? 'Hidden while editing' : 'Removed from sale' }}</small></span></label> }</div></section>
        <section class="editor-card"><header><h3>Organization</h3></header><div class="editor-fields"><label>Category<select formControlName="category">@for (item of categories; track item) { <option [value]="item">{{ item }}</option> }</select></label><label>SKU<input formControlName="sku" /></label><label>Inventory<input type="number" formControlName="inventory" /></label></div></section>
        <section class="editor-card publish-card"><header><h3>Publishing</h3></header><label><input type="checkbox" checked />Online store</label><label><input type="checkbox" checked />Point of sale</label><p>Last edited {{ id() ? 'today at 10:42 AM' : 'just now' }}</p></section>
      </aside></div>
    </form>
  `,
  changeDetection: ChangeDetectionStrategy.OnPush,
})
export class ProductEditorComponent {
  readonly ArrowLeft=ArrowLeft;readonly Check=Check;readonly Plus=Plus;readonly Save=Save;readonly Trash2=Trash2;readonly UploadCloud=UploadCloud; readonly id=input<string>(); private readonly fb=inject(FormBuilder);private readonly data=inject(AdminDataService);private readonly router=inject(Router);readonly categories=['Carry','Audio','Desk','Wear','Travel'];readonly saving=signal(false);readonly saved=signal(false);
  readonly form=this.fb.nonNullable.group({name:['',[Validators.required,Validators.minLength(2)]],slug:['',[Validators.required,Validators.pattern(/^[a-z0-9]+(?:-[a-z0-9]+)*$/)]],description:['',[Validators.required,Validators.minLength(20)]],category:['Carry',Validators.required],imageUrl:[''],price:[0,[Validators.required,Validators.min(0)]],comparePrice:[0,Validators.min(0)],cost:[0,Validators.min(0)],sku:['',Validators.required],inventory:[0,[Validators.required,Validators.min(0)]],status:['draft' as AdminProduct['status'],Validators.required],seoTitle:[''],seoDescription:[''],variants:this.fb.array([this.createVariant()])});
  get variants(){return this.form.controls.variants as FormArray} margin(){const price=this.form.controls.price.value,cost=this.form.controls.cost.value;return price?Math.round((price-cost)/price*100):0} profit(){return Math.max(0,this.form.controls.price.value-this.form.controls.cost.value).toFixed(2)}
  constructor(){effect(()=>{const id=this.id();if(!id)return;const p=this.data.product(id);if(p){this.form.patchValue({name:p.name,slug:p.slug,description:p.description,category:p.category,imageUrl:p.imageUrl,price:p.price,comparePrice:p.comparePrice??0,cost:p.cost,sku:p.sku,inventory:p.inventory,status:p.status,seoTitle:p.seoTitle,seoDescription:p.seoDescription});this.variants.clear();p.variants.forEach(v=>this.variants.push(this.createVariant(v)));}})}
  private createVariant(value?:AdminProduct['variants'][number]){return this.fb.nonNullable.group({id:[value?.id??crypto.randomUUID()],name:[value?.name??'Default',Validators.required],sku:[value?.sku??'',Validators.required],price:[value?.price??0,[Validators.required,Validators.min(0)]],inventory:[value?.inventory??0,[Validators.required,Validators.min(0)]]})} addVariant(){this.variants.push(this.createVariant())} removeVariant(index:number){if(this.variants.length>1)this.variants.removeAt(index)}
  async save(){if(this.form.invalid){this.form.markAllAsTouched();return}this.saving.set(true);const v=this.form.getRawValue();const existing=this.id()?this.data.product(this.id()!):undefined;const categoryId=existing?.categoryId??this.data.products().find((item)=>item.category===v.category)?.categoryId??'';const product:AdminProduct={id:existing?.id??'',name:v.name,slug:v.slug,description:v.description,category:v.category,categoryId,imageUrl:v.imageUrl||'https://images.unsplash.com/photo-1556742049-0cfed4f6a45d?auto=format&fit=crop&w=600&q=80',price:v.price,comparePrice:v.comparePrice||undefined,cost:v.cost,sku:v.sku,inventory:v.inventory,reserved:existing?.reserved??0,incoming:existing?.incoming??0,status:v.status,updatedAt:new Date().toISOString(),variants:v.variants,seoTitle:v.seoTitle,seoDescription:v.seoDescription};try{const saved=await this.data.saveProduct(product);this.saved.set(true);if(!this.id())await this.router.navigate(['/admin/products',saved.id]);setTimeout(()=>this.saved.set(false),2800)}finally{this.saving.set(false)}}
}
